### ISSUE TITLE
Press space to confirm the characters entered, with an extra space at the end

### ISSUE THREAD

**Issue by zhixu-xp** [fcitx/fcitx-hangul#10]
When I enter a character and press the space bar to confirm, a space will be added at the end, and the cursor will not follow the end of the last character.

current state
![current_20221031180155](https://user-images.githubusercontent.com/98310604/198984098-cd6159a6-4c21-4972-bdad-a8b429493027.gif)

Desired state

![Desired_20221031181056](https://user-images.githubusercontent.com/98310604/198984474-6261c8c7-e0d1-45fd-bad4-1b17925222c1.gif)

**Comment by soshimee** [comment]
Korean input methods do not require confirming any input. That box is appearing because the text editor does not completely support Korean input.
