### ISSUE TITLE
Can't type Korean unless the default keyboard is US(qwerty).

### ISSUE THREAD

**Issue by nemonein** [fcitx/fcitx-hangul#4]
I'm using Ubuntu 16.04x64 and fcitx up to dated version.

When the default keyboard is US qwerty, Korean input works fine.
However, if I use other than US qwerty, such as US-dvorak or colemak, it's impossible to type Korean properly. It is hard to tell, but easy to find out what I mean if you try.

It was not like this unitl Ubuntu 15.10.

**Comment by wengxt** [comment]
I can't reproduce it, though I'm not on ubuntu. may I have your fcitx-diagnose and ~/.config/fcitx/data/layout_override ?

**Comment by nemonein** [comment]
@wengxt  Thank you for your quick respose.

```
$cat .config/fcitx/data/layout_override 
hangul,us
```

I changed the settings, and .config/fcitx/data/layout_override file manually several other ways, but the results are the same.

I attached diagnose file.
[f-diag.zip](https://github.com/fcitx/fcitx-hangul/files/798424/f-diag.zip)

I want to make sure what happens.
When the Us-dvorak is the default keyboard, if I try to type ㅁ,ㄴ,ㄹ,ㅇ but the result is ㅁ, ㅐ, ㄷ, ㅕ.

I hope you can find what causes this.
Thank your for your concern!

**Comment by wengxt** [comment]
Ok, now I understand what you're trying to do. You're now typing ㅁ, ㅐ, ㄷ, ㅕ, because the corresponding key under dvorak, are for that. I'm aware that you already set hangul to use the qwerty layout. I think your problem is caused by new gnome shell. 

https://bugzilla.gnome.org/show_bug.cgi?id=756543 (note, this is a side effect of this bug fix, and they don't intend to change it to make it work for your case :( )

Which means under gnome-shell third party application are not allowed to change keyboard layout (keyboard layout group, to be more precisely).

Unfortunately, the only thing that I could recommend to you is for now, to use either ibus, or to use other desktop env, or to use a single keyboard layout.

**Comment by wengxt** [comment]
I could try to hack kimpanel-for-gnome-shell to use a hidden api in mutter, or to create a standalone gnome-shell extension, but that would take some time.

**Comment by nemonein** [comment]
I'm not using gnome-shell but Unity, but it might not different, doesn't it?
You recommend that use a single keyboard, that means either I choose English or Korean, but that means nothing to me. It means nothing to all Korean users. ^^

Thanks anyway.

**Comment by wengxt** [comment]
no, unity doesn't use mutter. so it could be a separate issue.

**Comment by wengxt** [comment]
I probably need to install a ubuntu to check anyway.. I received a report that another person on arch who uses de layout and a de layout variant, couldn't properly switch the layout properly too. Now I wonder if there's a bug in fcitx's xkb module, but I couldn't reproduce it locally so far.

**Comment by nemonein** [comment]
Thanks a lot.
I hope you try the original Ubuntu(Unity version) as well as Ubuntu-gnome.

**Comment by nemonein** [comment]
I shoud have told you that in some case, it works fine.
![fcitx-hangul-dvorak](https://cloud.githubusercontent.com/assets/5688288/23293541/ffac8b9a-faa9-11e6-83fc-ec378aeee92c.gif)

Please watch the gif file.
I'm typing A,O,E,U and ㅁ,ㄴ,ㄹ,ㅇ. Sometimes it works good, but sometimes ㅁ,ㅐ,ㄷ,ㅕ is triggered.
It's Ubuntu 16.04x64 on Virtual Box. Host OS is also Ubuntu 16.04x64.

However, on some machines(same OS: Ubuntu 16.04x64), always ㅁ,ㅐ,ㄷ,ㅕ are typed.

**Comment by wengxt** [comment]
I figured out it's actually gnome-settings-daemon is also trying to configure keyboard layout, and is causing some race.

For now, the easiest way to fix it for you is to disable the keyboard plugin in unity-settings-daemon. By execute following command

 gsettings set org.gnome.settings-daemon.plugins.keyboard active false

**Comment by wengxt** [comment]
Please aware that you'll not be able to use super+space to switch if you run the command above (which is handled by settings-daemon by default), you can still configure fcitx to use any key to trigger though.

Also I tried to add an workaround for this problem without disable the plugin, though it's not perfect solution.
https://github.com/fcitx/fcitx/commit/8b1fdf19abcd0ae71c13ffd1af6fa108d2c212fd

**Comment by nemonein** [comment]
It works. I should have asked you a year ago.
I can't thank you enough.
